### ISSUE TITLE
user defined database location

### ISSUE THREAD

**Issue by nick-youngblut** [victoriapascal/gutsmash_doc#2]
Currently gutSMASH requires that the databases be located at `gutsmash/antismash/databases/`. It would be helpful to allow the user to set the location of the databases, given that it is usually beneficial to keep large files and software separate (eg. having one database copy for users with their own software installs or 1 database for multiple version installs for the same user).

**Comment by nick-youngblut** [comment]
hmmm... the README in `gutsmash/antismash/databases/` states:

> A different location can be specified by use of the commandline option
--databases PATH, however it must have the same expected structure.
antismash/databases/README (END)

...but the `run_gutsmash.py` script docs don't include a `--databases` parameter.

**Comment by victoriapascal** [comment]
The desired location is in the folder of databases as specified. You can also use the `--databases` flag to specify where they are or as alternative, create symbolic links if you want to have them elsewhere.

**Comment by nick-youngblut** [comment]
Just to be clear, the `run_gutsmash.py` script doc now includes `--databases`? If so, thanks for the quick update!
